# Configuration for PHP generator
templateDir: .openapi-generator/generators/php/templates
variableNamingConvention: camelCase
invokerPackage: GarageWeek
modelPackage: PetStoreClient
packageName: oco-research/php-sdk
composerPackageName: oco-research/php-sdk
projectDescription: PHP SDK for Pet Store API
specProject: oco-research/openapi-spec
repoOrg: oco-research
repoName: php-sdk
files:
  .github/workflows/publish.yml:
    destinationFilename: .github/workflows/publish.yml
  docs/index.mustache:
    destinationFilename: docs/index.html
