templateDir: .openapi-generator/generators/javascript/templates
projectName: oco-research/nodejs-sdk
npmRepository: https://github.com/oco-research/nodejs-sdk
projectDescription: NodeJS SDK for Pet Store API
usePromises: true
