# Configuration for Javascript generator
templateDir: .openapi-generator/generators/javascript/templates
projectName: oco-research-nodejs-sdk
npmRepository: https://github.com/oco-research/nodejs-sdk
projectDescription: NodeJS SDK for Pet Store API
usePromises: true
specProject: oco-research/openapi-spec
repoOrg: oco-research
repoName: nodejs-sdk
files:
  .github/workflows/publish.yml:
    destinationFilename: .github/workflows/publish.yml
  docs/index.mustache:
    destinationFilename: docs/index.html
