name: Generate SDK

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  generate-sdk:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - generator: javascript
            github-owner: oco-research
            github-repo: nodejs-sdk
            github-branch: main
            github-token: REMOTE_GIT_TOKEN
            package-token: REMOTE_NPM_TOKEN
          - generator: php
            github-owner: oco-research
            github-repo: php-sdk
            github-branch: main
            github-token: REMOTE_GIT_TOKEN
            package-token: REMOTE_PACKAGIST_API_TOKEN
            package-username: REMOTE_PACKAGIST_USERNAME
          - generator: java
            github-owner: oco-research
            github-repo: java-sdk
            github-branch: main
            github-token: REMOTE_GIT_TOKEN

    steps:
      - name: Generate ${{ matrix.generator }} SDK
        uses: oco-research/sdk-generator@v1
        with:
          generator: ${{ matrix.generator }}
          github-owner: ${{ matrix.github-owner }}
          github-repo: ${{ matrix.github-repo }}
          github-branch: ${{ matrix.github-branch }}
          github-token: ${{ secrets[matrix.github-token] }}
          package-token: ${{ secrets[matrix.package-token] }}
          package-username: ${{ secrets[matrix.package-username] }}
