name: Generate SDK

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  generate-sdk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy .openapi-generator-ignore file to ignore files during generation
        run: mkdir javascript-client && cp .openapi-generator/generators/javascript/.openapi-generator-ignore javascript-client/

      - name: Generate JavaScript SDK
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: javascript
          config-file: .openapi-generator/generators/javascript/config.yml

      - name: Push changes to external repo
        env:
          REMOTE_GIT_TOKEN: ${{ secrets.REMOTE_GIT_TOKEN }}
        run: |
          OPENAPI_VERSION=$(cat openapi.json | python3 -c "import sys, json; print(json.load(sys.stdin)['info']['version'])")
          echo "OpenAPI Version: ${OPENAPI_VERSION}"
          git config --global user.email "devex-open-contribution-office@adobe.com"
          git config --global user.name "OCO SDK Generator"
          git config --global init.defaultBranch main
          git config --global pull.rebase false
          cd javascript-client
          git init
          git add .
          git commit -m "${OPENAPI_VERSION}"
          git remote add origin https://"$REMOTE_GIT_TOKEN"@github.com/oco-research/nodejs-sdk.git
          git pull origin main --allow-unrelated-histories -X ours
          git push origin main
