name: Generate SDK

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  generate-sdk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate JavaScript SDK
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: javascript
          config-file: .openapi-generator/generators/javascript/config.yaml

      - name: Get API version
        run: |
          OPENAPI_VERSION=$(cat openapi.json | python3 -c "import sys, json; print(json.load(sys.stdin)['info']['version'])")
          echo "OpenAPI Version: ${OPENAPI_VERSION}"

      - name: Push changes to external repo
        run: |
          git config --global user.email "devex-open-contribution-office@adobe.com"
          git config --global user.name "OCO SDK Generator"
          cd javascript-client
          git init
          git add .
          git commit -m "${OPENAPI_VERSION}"
          git remote add origin https://oco-research:${{ secrets.REMOTE_GIT_TOKEN }}"@github.com/oco-research/nodejs-sdk.git
          git pull origin main
          git push origin main 2>&1 | grep -v 'To https'
